package sl.fside.services.code_generator2.validation;

import sl.fside.services.code_generator2.model.*;

/**
 * Validate model generated by pattern.
 */
public interface Validator {
    void validate(Model model);
}
